name: chemprop
channels:
  - rdkit
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - _tflow_select=2.1.0=gpu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - amqp=5.2.0=pyhd8ed1ab_1
  - astor=0.8.1=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_0
  - billiard=3.6.4.0=py37h540881e_2
  - blas=1.0=mkl
  - bottleneck=1.3.5=py37hda87dfa_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.3=hb9d3cd8_1
  - ca-certificates=2025.11.4=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.14.12=h8948797_3
  - celery=5.2.7=pyhd8ed1ab_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - click=8.1.3=py37h89c1867_0
  - click-didyoumean=0.3.1=pyhd8ed1ab_0
  - click-plugins=1.1.1=py_0
  - click-repl=0.3.0=pyhd8ed1ab_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cudatoolkit=11.3.1=hb98b00a_13
  - cycler=0.11.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.9=h5eee18b_2
  - flask=2.2.5=pyhd8ed1ab_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.38.0=py37h540881e_0
  - freetype=2.12.1=h267a509_2
  - future=0.18.2=py37h89c1867_5
  - gast=0.5.5=pyhd8ed1ab_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.6.13=h85f3911_1
  - gpy=1.10.0=py37hda87dfa_3
  - grpcio=1.46.3=py37h0327239_0
  - h5py=3.7.0=nompi_py37hf1ce037_101
  - hdf5=1.12.2=nompi_h4df4325_101
  - hyperopt=0.2.7=pyhd8ed1ab_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=4.11.4=py37h89c1867_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py37h7cecad7_0
  - kombu=5.2.4=py37h89c1867_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcurl=8.8.0=hca28451_1
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.8.0=h8b12597_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.4.0=h82bc61c_5
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.50.0=hb9d3cd8_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxgboost=1.5.1=h6a678d5_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.13=h4ab18f5_6
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.1=py37h540881e_1
  - matplotlib-base=3.5.3=py37hf395dca_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - mock=5.1.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=he02047a_1
  - nettle=3.6=he412f7d_0
  - networkx=2.7=pyhd8ed1ab_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - numexpr=2.8.4=py37he184ba9_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.4.1=h7b32b05_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.3.5=py37h8c16a72_0
  - paramz=0.9.6=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - pillow=9.2.0=py37h850a105_2
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.40.0=h7f8727e_1
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - protobuf=3.8.0=py37he1b5a44_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - py-boost=1.73.0=py37h51133e4_12
  - py-xgboost=1.5.1=py37h06a4308_0
  - py4j=0.10.9.7=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.7=4_cp37m
  - pytorch=1.10.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2024.2=pyhd8ed1ab_0
  - rdkit=2020.09.1.0=py37hd50e099_1
  - readline=8.2=h8228510_1
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37h6c91a56_2
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.46.0=h6d4b2fc_0
  - statsmodels=0.13.2=py37hda87dfa_0
  - tensorboard=1.13.1=py37_0
  - tensorboardx=2.5.1=pyhd8ed1ab_0
  - tensorflow=1.13.1=h5ece82f_5
  - tensorflow-base=1.13.1=py37h5ece82f_5
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchvision=0.11.0=py37_cu113
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - unicodedata2=14.0.0=py37h540881e_1
  - vine=5.1.0=pyhd8ed1ab_0
  - wcwidth=0.2.10=pyhd8ed1ab_0
  - werkzeug=2.2.3=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xgboost=1.5.1=py37h06a4308_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.2.6=h166bdaf_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - alembic==1.12.1
      - antlr4-python3-runtime==4.9.3
      - ase==3.22.1
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - attrs==24.2.0
      - charset-normalizer==3.4.1
      - colorlog==6.9.0
      - dill==0.3.7
      - dirsync==2.2.5
      - fasteners==0.19
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - greenlet==3.1.1
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - idna==3.10
      - importlib-resources==5.12.0
      - lark-parser==0.12.0
      - lightning-utilities==0.10.1
      - mako==1.2.4
      - markdown-it-py==2.2.0
      - matscipy==1.0.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.15
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - omegaconf==2.3.0
      - optuna==4.0.0
      - pandas-flavor==0.6.0
      - pathos==0.3.1
      - pox==0.3.3
      - ppft==1.7.6.7
      - psutil==6.1.0
      - pygments==2.17.2
      - pytorch-lightning==1.9.5
      - pyyaml==6.0.1
      - requests==2.31.0
      - rich==13.8.1
      - schnetpack==1.0.1
      - sqlalchemy==2.0.44
      - sympy==1.10.1
      - torch-ema==0.3
      - torchani==2.2.4
      - torchaudio==0.13.1+cu117
      - torchmetrics==0.11.4
      - urllib3==2.0.7
      - xarray==0.20.2
      - yarl==1.9.4
prefix: /home/xianyus/anaconda3/envs/chemprop
